image:
  file: Dockerfile.gitpod

ports:
  - name: Docs
    port: 4200
    onOpen: open-preview
  - name: Storybook
    port: 3000
    onOpen: open-preview
  - name: Postgres
    port: 5432
    onOpen: ignore

tasks:
  - name: Setup
    init: |
      yarn install
      yarn e2e:setup
      gp sync-done setup
    openMode: split-left
  - name: Start
    init: gp sync-await setup
    command: yarn start
    openMode: split-right
