name: CI

on:
  push:
    branches:
      - main
      - experimental
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    container:
      image: ghcr.io/bit-tasks/stable:latest-alpine # Use GitHub Container Registry image
      options: --user root

    env:
      BIT_CONFIG_ACCESS_TOKEN: 'secret'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Node.js installation
        run: node -v

      - name: Verify Git installation
        run: git -v

      - name: Initialize Bit
        uses: bit-tasks/init@main
        with:
          ws-dir: ${{ github.workspace }}
          ripple: false
          log: 'trace'

      # - name: Setup NPM Registries
      #   run: |
      #     npm config set '@bit:registry' https://node-registry.bit.cloud
      #     npm config set '@teambit:registry' https://node-registry.bit.cloud
      #     npm config set //node-registry.bit.cloud/:_authToken ${{ env.BIT_CONFIG_ACCESS_TOKEN }}

      - name: Verify Install
        run: |
          node -v
          bit -v
          which bit
          echo "WSDIR=${WSDIR}"
          echo "RIPPLE=${RIPPLE}"
          echo "LOG=${LOG}"
          echo "CACHE=${CACHE}"
          echo "ORG=${ORG}"
          echo "SCOPE=${SCOPE}"
          echo "BIT_CONFIG_ANALYTICS_REPORTING=${BIT_CONFIG_ANALYTICS_REPORTING}"
          echo "BIT_CONFIG_ANONYMOUS_REPORTING=${BIT_CONFIG_ANONYMOUS_REPORTING}"
          echo "BIT_CONFIG_INTERACTIVE=${BIT_CONFIG_INTERACTIVE}"
          echo "PATH=${PATH}"
          echo "BIT_DISABLE_CONSOLE=${BIT_DISABLE_CONSOLE}"
          echo "BIT_DISABLE_SPINNER=${BIT_DISABLE_SPINNER}"
